### ISSUE TITLE
Working idea #2: #ossoapbox

### ISSUE THREAD

**Issue by emmyft** [emmyft/mozfest19#3]
(This is very much based on the idea for Mozfest 2017 from @npscience )

Motivations:
- give open science open-source innovators a space to get feedback from a diverse audience, and practice their communication
- give the audience an idea of the latest innovations in the open science problem domain, and how they can contribute
- show people that it's possible to initiate grassroots changes and projects!

Format:
- lightning talks (with specific CTA) + heavy Q&A (This could replace the open-source community call that is supposed to happen in Oct 2019)
- sketch notes? 
- live tweets @eLifeInnovation
- remote presentations

Risks:
- What if no one asks questions?
- The audience doesn't understand– how to better engage?

Options to explore:
- Theme: AI? 
- What projects to include, do we organise an open agenda like we do the open-source community calls? 
- Do we entertain spontaneous project additions? (Yes!)

**Comment by npscience** [comment]
And this happened organically in 2018 with @marcosvital leading 🌟

**Comment by npscience** [comment]
Re sketch notes: hiring professional = £££ and difficult to wrangle on a weekend (I thought about it for 2017). So is there someone in the community who'd like to try this out? Or several people to take turns? I think visual notes are wonderful keepsakes (and can be displayed and shared on social, etc)

If I go to Mozfest, I would volunteer to live sketch 1 or 2 talks!

**Comment by emmyft** [comment]
I'm thinking exactly having people take turns! Or any volunteers? I can also ask around eLife (the argument is strong: it's a much more digestible record of the talks, and tend to gain good social traction)

My biggest worry is still not gathering a big enough audience. I also think it's important to make sure we can live stream it (even if just audio) and accept remote questions. Does anyone have ideas on how that could be done?

**Comment by emmyft** [comment]
I've just started a draft for the proposal! See #4 

Closing this issue and moving all discussion to the pull request #4  (:
