### ISSUE TITLE
potential presenters

### ISSUE THREAD

**Issue by emmyft** [emmyft/mozfest19#7]
Continuing from #4's discussion

* something from eLife @de-code
* Open Knowledge Maps
* Scite.ai
* Projects from eScience? @mkuzak could you please approach?
* Projects from the Turing? @Biostew

**Comment by emmyft** [comment]
updates -

* Peter @ OK maps said yes, they are not sure if they would be there physically at MozFest, but can definitely do at least a remote presentation
* From eLife, there will most likely be 2 projects that we can present, on using AI and ML to abstract research output, and in peer review processes
* @Biostew is happy to present on FAIR at BL/Datacite - would be better if focussed on /targeted towards work related AI (:

**Comment by c-martinez** [comment]
Hi @emmyft -- @mkuzak mentioned this initiative to me. We were discussing it this morning, and could he mentioned you had in mind focusing on natural language processing / text analysis. But actually on this repo I cannot find any reference to it.

Basically my question boils down to: is there any specific focus of AI / ML tools which would be interesting for this session?

**Comment by emmyft** [comment]
Hi @c-martinez – thanks for the question! 

I feel like we're interested in AI/ ML tools in general in this session – but since I work on research communication (discovery, consumption, sharing and evaluation), many tools naturally fall into the NLP/text analysis bucket. Both of the projects we're thinking of presenting from eLife will involve text analysis.

We're open to ideas! I know @biostew is keen on ideas on FAIR... so we may very well have a mix of presentations in the end (:

**Comment by c-martinez** [comment]
Ok, so ML for timeseries analysis would be in scope. I think we could talk about a few eScience center projects which use ML :-)

**Comment by mkuzak** [comment]
@c-martinez are you thinking of [mcfly](https://github.com/NLeSC/mcfly) then?

**Comment by c-martinez** [comment]
Yes. And I think we could show some results from other projects, although those would mostly use existing tools (keras, pytorch, etc), so I am not sure if they are of interest to this session.

**Comment by mkuzak** [comment]
I think if it's the application of existing tools leading to interesting research results, that should fit too.

**Comment by emmyft** [comment]
While we're still waiting for the proposal decision...

- looping in @chreman for OK maps: he is interested in attending in person, we will try to secure travel funding
- there are probably a few potentials coming up next week at the eLife Sprint too; I'll keep an eye out for them

**Comment by emmyft** [comment]
Folks - unfortunately the proposal has not been accepted for MozFest. I am keen to run a community call on open-source projects/tools for open science using AI though, I'll be in touch with further information and you are all invited (:

Thank you very much for your interest and effort!

**Comment by c-martinez** [comment]
Hi @emmyft -- sorry to hear that :-(

Open source tools for open science using AI -- would it be suitable to organise a workshop on that in the context of [nl-rse](https://nl-rse.org/2019/07/09/NL-RSE-2019.html) ?

**Comment by emmyft** [comment]
We are running a community call in lieu of this MozFest proposal on Oct 29 (Tuesday), 3pm GMT/4pm ET. More information [here](https://elifesciences.org/events/454a2e98/open-source-community-call-the-latest-developments-in-ai-and-machine-learning-tools-for-open-science) and register [here](https://register.gotowebinar.com/register/6488840840683663371) !

Hope to see you on the call – and at MozFest, if you are attending (: Thanks!
